from __future__ import annotations

import json
import logging
from typing import Any

from pydantic import BaseModel, Field

from app.services.azure_openai import azure_openai
from app.prompts.questions import QUESTION_GENERATION_PROMPT


class QuestionSchema(BaseModel): #schema used when extracting questions from llm
    question_order: int
    question_text: str
    skill_area: str = Field(description="General area of the skill being evaluated")
    difficulty: str = Field(description="basic | intermediate | advanced")

class GeneratedQuestions(BaseModel):#schema used to store questions generated by llm
    questions: list[QuestionSchema]

#  Service
logger = logging.getLogger(__name__)

_FALLBACK_QUESTIONS = [
    {"question_order": 1, "question_text": "Can you tell me about your background?", "skill_area": "General", "difficulty": "basic"},
    {"question_order": 2, "question_text": "What was your most challenging project?", "skill_area": "Experience", "difficulty": "intermediate"},
]

class QuestionService:
    """generates interview questions from resume, JD, and skill gaps."""
    async def generate(
        self,
        resume_json: dict[str, Any],
        jd_json: dict[str, Any],
        skill_gap_report: dict[str, Any],
        num_questions: int = 8,
    ) -> list[dict]: #Return a list of question dicts (question text, skill area & difficulty).
        num_questions = max(6, min(10, num_questions))

        payload = json.dumps(
            {"resume": resume_json, "job_description": jd_json, "skill_gap_report": skill_gap_report},
            indent=2,
        )

        try:
            result: GeneratedQuestions = await azure_openai.extract_structured_data(
                raw_text=payload,
                prompt_template=QUESTION_GENERATION_PROMPT,
                response_model=GeneratedQuestions,
                llm=azure_openai.smart_llm,
                num_questions=num_questions,
            )
            questions = [q.model_dump() for q in result.questions]

            if not questions:
                logger.warning("LLM returned empty questions — using fallback.")
                return _FALLBACK_QUESTIONS

            logger.info("Generated %d questions.", len(questions))
            return questions[:num_questions]

        except Exception as exc:
            logger.error("QuestionService.generate failed: %s", exc)
            raise

question_service = QuestionService()
